version: 2

sources:
  - name: LANDING
    database: SLEEKMART_OMS
    schema: L1_LANDING
    tables:
      - name: CUSTOMERS
      - name: ORDERS
      - name: DATES
      - name: EMPLOYEES
      - name: PRODUCTS
      - name: STORES
      - name: SUPPLIERS
      - name: ORDERITEMS

  - name: sales
    database: SLEEKMART_OMS
    schema: SALES
    tables:
      - name: city_temperature
      - name: sales_us
      - name: sales_uk
      - name: sales_india
